# Generated by Django 2.1.1 on 2018-11-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokenChains', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together=set(),
        ),
    ]
