# Generated by Django 2.1.3 on 2018-12-17 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokenChains', '0003_auto_20181106_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 12, 17)),
        ),
        migrations.AlterField(
            model_name='habit',
            name='stop_date',
            field=models.DateField(default=datetime.date(2019, 1, 7)),
        ),
    ]
